name: flutter_audio_playlist_example
description: Example app to test the flutter_audio_playlist package
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  just_audio_background: any
  flutter_audio_playlist:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true